### PR TITLE
added README.zh.md (SimpChinese)

### PR DESCRIPTION
**Pull request by CacPixel**
added Chinese Readme

### CODE REVIEW

**Comment by anatawa12** [comment]
@CacPixel I've updated README a little & updated the github actions.
Can you merge the upstream & update README?

**Comment by CacPixel** [comment]
Done :>

**Comment by CacPixel** [comment]
@anatawa12 Done :>

**Review by anatawa12 — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
