### PR TITLE
move render-gear.js

### LINKED ISSUE #112: render-gear.js
crash: [crash-2020-08-17_03.18.08-client.txt](https://github.com/fixrtm/fixRTM/files/5081611/crash-2020-08-17_03.18.08-client.txt).

Well, RTM crashes with fixRTM. Problem in DummyModelSetMechanism.class: render-gear.js

### PR DESCRIPTION
**Pull request by anatawa12**
fixes #112

### CODE REVIEW

**Comment by EVgenyGP** [comment]
Hello anatawa12, this message is clearly off topic, but how can I contact you? if necessary, I will delete this message without any problems.

**Comment by anatawa12** [comment]
@EVgenyGP The reason for your crash is script loader of normal RTM cannot resolve `"fix-rtm:scripts/render-gear.js"` because RTM only supports `minecraft` domain. so I moved the script file to `"minecraft:fix-rtm/scripts/render-gear.js"`.

**Comment by EVgenyGP** [comment]
@anatawa12 I know the reason for the crash and even fixed it for RTM 20 + fixRTM 2.0.12, my friends and I keep the Russian-speaking community metant (https://vk.com/rtm_russian) and I would like to have contacts with you to pass rare crashes with problems related to fixRTM, we can keep in touch via discord?

**Comment by EVgenyGP** [comment]
So? email: evgenygp@mail.ru or evgenygpg@gmail.com, discord: 𝓔𝓥𝓰𝓮𝓷𝔂𝓖𝓟#8232

**Comment by anatawa12** [comment]
my friend says this bug is reproduced so I fixed this bug.

> I would like to have contacts with you to pass rare crashes with problems related to fixRTM, we can keep in touch via discord?

I planned to make a discord server for fixrtm so I made a discord server for fixrtm. please join discord server: https://discord.gg/qFKcUXX

**Pull request merged**
